### PR TITLE
Default union type resolver

### PR DESCRIPTION
**Pull request by pawelrubin**
## Problem

Currently handling **UnionTypes** requires writing a boiler-plate type resolver. It tends to be irritating, especially for big unions.

Example from [docs](https://ariadnegraphql.org/docs/next/unions#union-example):
```python
from ariadne import UnionType

error = UnionType("Error")

@error.type_resolver
def resolve_error_type(obj, *_):
    if isinstance(obj, ValidationError):
        return "ValidationError"
    if isinstance(obj, AccessError):
        return "AccessError"
    return None
```

## Solution
Default type resolver. You can still set a custom `type_resolver`, but the common behaviour is the default.

```python
def default_type_resolver(obj: Any, *_: Any) -> str:
    return type(obj).__name__
```

### CODE REVIEW

**Comment by pawelrubin** [comment]
PR ready for review, although I'm not sure why the codecov/project check failed.

**Comment by rafalp** [comment]
Thanks for opening this PR!

Looking good, but I'm wondering if we could (or should) somehow combine this with default behavior provided by the GraphQL executor when no type resolver is defined: accessing object's `__typename` attribute (or dict key) to see if typename is already defined on object.

**Comment by pawelrubin** [comment]
Hi @rafalp. Thanks for the quick response.

I'm not sure if I follow. Do you mean to check for the presence of `obj["__typename"]` in the `make_default_type_resolver`?

**Comment by rafalp** [comment]
Yes.

**Comment by pawelrubin** [comment]
That's an interesting point. I'll look into that.

**Comment by patrys** [comment]
I think it may actually be easier to explicitly define the `__typename` on these types instead of writing a custom union resolver.

**Comment by pawelrubin** [comment]
The [graphql-core](https://github.com/graphql-python/graphql-core/blob/master/src/graphql/execution/execute.py#L1224) codebase provides default resolvers. Both for fields and types.

```python

def default_type_resolver(
    value: Any, info: GraphQLResolveInfo, abstract_type: GraphQLAbstractType
) -> AwaitableOrValue[Optional[Union[GraphQLObjectType, str]]]:
    """Default type resolver function.

    If a resolve_type function is not given, then a default resolve behavior is used
    which attempts two strategies:

    First, See if the provided value has a ``__typename`` field defined, if so, use that
    value as name of the resolved type.

    Otherwise, test each possible type for the abstract type by calling
    :meth:`~graphql.type.GraphQLObjectType.is_type_of` for the object
    being coerced, returning the first type that matches.
    """
    # First, look for `__typename`.
    type_name = get_typename(value)
    if isinstance(type_name, str):
        return type_name

    # Otherwise, test each possible type.
    possible_types = info.schema.get_possible_types(abstract_type)
    is_awaitable = info.is_awaitable
    awaitable_is_type_of_results: List[Awaitable] = []
    append_awaitable_results = awaitable_is_type_of_results.append
    awaitable_types: List[GraphQLObjectType] = []
    append_awaitable_types = awaitable_types.append

    for type_ in possible_types:
        if type_.is_type_of:
            is_type_of_result = type_.is_type_of(value, info)

            if is_awaitable(is_type_of_result):
                append_awaitable_results(cast(Awaitable, is_type_of_result))
                append_awaitable_types(type_)
            elif is_type_of_result:
                return type_

    if awaitable_is_type_of_results:
        # noinspection PyShadowingNames
        async def get_type():
            is_type_of_results = await gather(*awaitable_is_type_of_results)
            for is_type_of_result, type_ in zip(is_type_of_results, awaitable_types):
                if is_type_of_result:
                    return type_

        return get_type()

    return None


def default_field_resolver(source: Any, info: GraphQLResolveInfo, **args: Any) -> Any:
    """Default field resolver.

    If a resolve function is not given, then a default resolve behavior is used which
    takes the property of the source object of the same name as the field and returns
    it as the result, or if it's a function, returns the result of calling that function
    while passing along args and context.

    For dictionaries, the field names are used as keys, for all other objects they are
    used as attribute names.
    """
    # Ensure source is a value for which property access is acceptable.
    field_name = info.field_name
    value = (
        source.get(field_name)
        if isinstance(source, dict)
        else getattr(source, field_name, None)
    )
    if callable(value):
        return value(info, **args)
    return value
```


I think they could be imported by **ariadne**. What do You think @rafalp @patrys?

**Comment by pawelrubin** [comment]
I've added the `default_type_resolver`. Since the default behavior is the same as the one achieved with `make_default_type_resolver`, I've deleted it.

I think this is ready for the review.

**Comment by pawelrubin** [comment]
Hi @rafalp @patrys. Any chance for a review/comments? 🙏

**Review by rafalp — CHANGES_REQUESTED** [review]
Default type resolver should still respect `__typename` dict key/obj attribute.

**Comment by rafalp** [comment]
Going for object's name is acceptable fallback, but only if there's no `__typename` attribute (or dict key when resolver's return value is dict).

I'm also unsure what happens when type resolver returns type name that's not present in the schema. This needs to be checked because for dict typename will resolve to `dict` (it should resolve to `None` instead).

**Comment by rafalp** [comment]
As said above having `__typename` may be easiest solution for the problem. In `graphql-modules` we may eventually implement option for types do declare their python representation enabling us to write "clean" default resolver for it's `UnionType`.

Thank you for contributing and sorry for taking two years for this :(

**Pull request closed without merging**
