### PR TITLE
Change supported starlette versions to include 0.14

### PR DESCRIPTION
**Pull request by cancan101**

### CODE REVIEW

**Comment by rafalp** [comment]
Did you mean include `0.15`? ;)

**Comment by cancan101** [comment]
> Did you mean include `0.15`? ;)

I don't think so. 0.14 has been released whereas 0.15 has not: https://www.starlette.io/release-notes/

**Comment by cancan101** [comment]
To avoid issues with pre-releases this would probably be better written as `<= 0.14.99`, but I kept as is for consistency.

**Comment by rafalp** [comment]
Ah, right, my mistake. Tests are passing, but linters are failing because updated Mypy is finding types errors. I'll accept this still.

**Review by rafalp — APPROVED** [review]

**Comment by cancan101** [comment]
Should this be accepted, though? It seems like the API in starlette might have changed causing these errors?

**Comment by rafalp** [comment]
No - only errors linters found are in types mismatch between the library and graphql-core.

**Comment by cancan101** [comment]
Oh, interesting. What caused that, a change in the deps for starlette? and either way, any reason for concern here?

**Comment by rafalp** [comment]
I've merged the PR from dependabot bumping mypy to latest versions in the meantime - that caused it.

> any reason for concern here?

Nope. We have quite a good unit tests suite in place for Ariadne, and that one is sitting on the top of tests suites for graphql-core and Starlette.

**Pull request merged**
