### PR TITLE
Use `execute_sync` instead of `execute` in `graphql_sync`

### LINKED ISSUE #823: Use `execute_sync` in `graphql_sync`
`graphql_sync` should use `execute_sync` instead of `execute`.

I run my code in a synchronous context, but a resolver was identified as asynchronous due to the fact that GraphQL core does a simple `hasattr(value, "__await__")` check instead of using `inspect.isawaitable`. This caused a false positive.

However, when using `graphql_sync` I expect that this check does not even happen. Consider using [`execute_sync`](https://github.com/graphql-python/graphql-core/blob/27768d3faac5bb8ebb2c6a151a7192b7fa498f2f/src/graphql/execution/execute.py#L1061) instead.

### PR DESCRIPTION
**Pull request by louwers**
Fixes #823

### CODE REVIEW

**Comment by tmc** [comment]
@rafalp PTAL.

**Comment by rafalp** [comment]
This is on the list to check for 0.15 release.

**Review by rafalp — APPROVED** [review]

**Comment by rafalp** [comment]
For some reason GitHub decided it won't be running PR checks for other people, but I've checked this branch locally and tests are passing.

**Comment by rafalp** [comment]
Thank you!

**Pull request merged**
