### PR TITLE
remove max version limit for graphql-core

### PR DESCRIPTION
**Pull request by tonyrewin**
then gql will support more async transports

### CODE REVIEW

**Comment by rafalp** [comment]
I don't like this change on a basis that people installing Ariadne will have to keep up themselves with it's compatibility with future GraphQL Core releases. And when those are incompatible, we will be the first ones to take heat for it, as we've been in the past.

**Comment by rafalp** [comment]
Which async transport do you want to use that's currently not supported by Ariadne?

**Comment by tonyrewin** [comment]
> Which async transport do you want to use that's currently not supported by Ariadne?
> 
> I understand you want to use GraphQL Core 3.3 alpha - other ways exist to do this like having custom version of Ariadne on GitHub and installing that one instead of `ariadne` from Pypi.

i wanted to use httpx for the latest only version of gql

**Comment by rafalp** [comment]
Sorry for late response but this is **not** going to happen. If you need Ariadne with GraphQL Core 3.3, please make a fork. Unpinning this dependency from Ariadne is a recipe for disaster.

**Pull request closed without merging**
