### PR TITLE
Update graphql-core-next to 1.1.1

### PR DESCRIPTION
**Pull request by rafalp**
This PR updates `graphql-core-next` to 1.1.1, fixing our tests failures.

### CODE REVIEW

**Comment by hvdklauw** [comment]
Also don't see the actual update of graphql-core-next in the changeset.

**Comment by rafalp** [comment]
@hvdklauw we don't really freeze `graphql-core-next` version to any specific number, and its maintainer has announced that next major release will happen as `graphql-core` package.

**Comment by hvdklauw** [comment]
You are right for the setup.py, but the [requirements.txt](https://github.com/mirumee/ariadne/blob/master/requirements.txt) actually does have a frozen version.

**Comment by rafalp** [comment]
Nice catch, I'll fix that one too 👍

**Pull request merged**
