### PR TITLE
Django serializer mutation resolver

### PR DESCRIPTION
**Pull request by maxmorlocke**
This PR provides a mutation resolver that is tightly coupled with Django REST Framework's ModelSerializer.  This allows mutations to be quickly and easily configured to perform validation and create, update, and delete operations leveraging a known, highly reliable, well documented, and performant solution.

This solution follows the outline setup by DRF's ModelViewSet.

Documentation PR: https://github.com/mirumee/ariadne-website/pull/59

### CODE REVIEW

**Comment by kedlav** [comment]
This should be ready for review

**Comment by rafalp** [comment]
We'll pass on this landing in `ariadne.contrib.django`, with the caveat being that we want to split all django-specific code from Ariadne into separate package (like `django-ariadne`). Merging this only to remove it in next release seems counterproductive.

I'll see when I can get the ball rolling on this. Likely will share more details on spectrum when I have the details.

**Comment by kedlav** [comment]
> We'll pass on this landing in `ariadne.contrib.django`, with the caveat being that we want to split all django-specific code from Ariadne into separate package (like `django-ariadne`). Merging this only to remove it in next release seems counterproductive.
> 
> I'll see when I can get the ball rolling on this. Likely will share more details on spectrum when I have the details.

That makes sense.  Let me know if there's anything I can do to help.  I'm happy to be a contributor in whatever way y'all feel is best to package things up.  We're really happy as ariadne+django users.

**Comment by nanorepublica** [comment]
I would be happy to be part of this conversation as I have built a similar MutationResolver that couples with DRF. I would need to check if I have permission to share the code first but definitely want to help make ariadne + django better!

**Pull request closed without merging**
