### PR TITLE
feat: improved alias resolvers (#1181)

### LINKED ISSUE #1181: set_alias support for nested attributes
I have a use case where the parent resolver returns something like this:

`Person(name="John", state=PersonState(married=False))`

To implement `person { married }`, you would need to create a new resolver returning `parent.state.married`, and in a large schema, there are many of these trivial resolvers.

It would be great if `set_alias` supported nested attributes, so one could do `person.set_alias("married", "state.married")`, maybe using `operator.attrgetter` instead of `getattr`.

### PR DESCRIPTION
**Pull request by dacevedo12**
- added support for resolving trivial nested fields

Closes #1181

### CODE REVIEW

**Comment by dacevedo12** [comment]
There seems to be a flaky unrelated test

**Comment by DamianCzajkowski** [comment]
Hi @dacevedo12 those failing tests are fixed on the main, try to merge it and it should be fine :D

**Comment by dacevedo12** [comment]
Indeed, thanks. CI is now green

**Comment by DamianCzajkowski** [comment]
LGTM! Please add a changelog entry, and I'll merge it. :D

**Review by DamianCzajkowski — APPROVED** [review]

**Comment by dacevedo12** [comment]
Changelog entry added 🚀

**Pull request merged**
