### PR TITLE
Federated graph regex performance. 

### PR DESCRIPTION
**Pull request by Mainian**
The main performance problem comes from `(?:\"{3}(?:[^\"]|[\s])*?\"{3})`.

The lazy '*?' drastically kills the performance of any federated graph that uses block comments, even if that graph is valid and has no custom directives.

Additionally, the old solution creates a run away regex with something like this: (4 quotes)
```
        """"
        Any Description
        """
        directive @custom on FIELD
        
        type Query {
            rootField: String @custom
        }
```

New solution will just ignore this comment.
```
        """"
        Any Description
        """
        
        type Query {
            rootField: String @custom
        }
```

### CODE REVIEW

**Comment by Mainian** [comment]
@rafalp 
`pull_request_target` runs against the workflow and code from the 'base' pull request instead of from the merge commit.

**Review by rafalp — APPROVED** [review]

**Comment by rafalp** [comment]
I see, but it was also supposed to run checks on PR's made by first time contributors? 🤔 

I've used `pull_request` previously and it didn't run checks at all. 🤨

Either way this is looking good. Thanks!

**Comment by Mainian** [comment]
@rafalp 
15.0 is basically unusable if you have any multi-line comments in your `types_defs`. 

Does if make sense to push this as a bug fix?

**Comment by rafalp** [comment]
I guess we can release this as 0.15.1 tomorrow. :)

**Comment by rafalp** [comment]
I've had some delay with this but I'll release this today.

**Comment by rafalp** [comment]
@Mainian released!

**Pull request merged**
